module instruction_memory (
    input wire [31:0] pc_address,
    output wire [31:0] instruction
);

    // Create our physical memory: 64 slots, each 32-bits wide
    reg [31:0] rom [0:63];

    // Load the hex file generated by your C++ assembler
    initial begin
        // Make sure "machine_code.hex" is in the same directory when simulating!
        $readmemh("../assembler/machine_code.hex", rom); 
    end

    // Fetch the instruction.
    // We use pc_address[31:2] to divide the address by 4 (ignoring the last 2 bits).
    assign instruction = rom[pc_address[31:2]];

endmodule